refactor filecheck

diff --git a/scripts/file_setup b/scripts/file_setup
--- a/scripts/file_setup
+++ b/scripts/file_setup
@@ -5,43 +5,47 @@
 ## usage: provide input directory
 
 function check_files() {
-    if [ -d "${1}" ]; then
-        printf "${1} \033[1m\033[36m OK \033[0m\n"
-        ### checking fastq extension --> ".gz"
-	    shopt -s nullglob
-		for file in "${1}"/*.{fq,fastq,fastq.gz}
-		    do
-			    if [[ "${file}" =~ \.fastq$ ]] || [[ "${file}" =~ \.fq$ ]]; then
-				    gzip "${file}"
-					printf "${file} \033[1m\033[36m OK \033[0m\n...compressing...\n"
-			    elif [[ "${file}" =~ \.gz$ ]]; then
-				    printf "${file} \033[1m\033[36m OK \033[0m\n"
-				else
-					echo
-					printf "\033[1m\033[31mError!! wrong extension in raw data\033[0m\n"
-					exit 1
-			    fi
-		done
-    else
-        printf "\033[1m\033[31m Error: ${1} not found. Cannot continue.\033[0m\n"
-        exit 1
-    fi
+	RAW_DATA="${1}"
+	while true; do
+		if [ -d "${RAW_DATA}" ]; then
+			printf "${RAW_DATA} \033[1m\033[36m OK \033[0m\n"
+			### checking fastq extension --> ".gz"
+			shopt -s nullglob
+			for file in "${RAW_DATA}"/*.{fq,fastq,fastq.gz}
+				do
+					if [[ "${file}" =~ \.fastq$ ]] || [[ "${file}" =~ \.fq$ ]]; then
+						gzip "${file}"
+						printf "${file} \033[1m\033[36m OK \033[0m\n...compressing...\n"
+					elif [[ "${file}" =~ \.gz$ ]]; then
+						printf "${file} \033[1m\033[36m OK \033[0m\n"
+					else
+						echo
+						printf "\033[1m\033[31mError!! wrong extension in raw data\033[0m\n"
+						exit 1
+					fi
+			done
+		break
+		else
+			printf "\033[1m\033[31m Error: ${RAW_DATA} not found. Cannot continue.\033[0m\n"
+			echo
+			
+			read -p "Please, provide raw data directory here: " userdir
+			export RAW_DATA="${userdir}"
+		fi
+	done
 }
-
 
 
 ##Check if destination exists, otherwise it creates it
 ## usage: provide directory to check
 
-function check_dir() {
+function check_outdir() {
 	if [ -d "${1}" ]; then
 		echo
   		printf "${1} OK\n"
-		printf "Creating subdirectories\n"
-  		mkdir -p ${1}/{fastqc,crispresso}
 	else
 		echo
   		printf "${1} not found. Creating....\n"
-  		mkdir -p ${1}/{fastqc,crispresso}
+		mkdir "${1}"
 	fi
 }
